version: '3.8'

services:
  selenoid:
    image: aerokube/selenoid:latest
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - ./config:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.44
    command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "4", "-timeout", "60s", "-container-network", "gameops-tests_default"]
    restart: unless-stopped